name: tutorprovide
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  page_transition: ^2.0.5
  url_launcher: ^6.0.20
  connectivity_plus: ^2.2.1
  carousel_slider: ^4.0.0
  webview_flutter: ^3.0.1
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  assets:
    - assets/
  fonts:
     - family: MyFlutterApp
       fonts:
         - asset: fonts/MyFlutterApp.ttf

  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
